# Generated by Django 5.0.1 on 2025-11-22 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(db_column='codigo_empleado', max_length=20, unique=True)),
                ('nombres', models.CharField(db_column='nombres', max_length=100)),
                ('apellidos', models.CharField(db_column='apellidos', max_length=100)),
                ('dpi', models.CharField(blank=True, db_column='dpi', max_length=25, null=True, unique=True)),
                ('nit', models.CharField(blank=True, db_column='nit', max_length=25, null=True)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=30, null=True)),
                ('email', models.EmailField(blank=True, db_column='email', max_length=150, null=True)),
                ('puesto', models.CharField(db_column='puesto', max_length=100)),
                ('area_trabajo', models.CharField(blank=True, db_column='area_trabajo', max_length=50, null=True)),
                ('turno', models.CharField(blank=True, db_column='turno', max_length=50, null=True)),
                ('tipo_contrato', models.CharField(blank=True, db_column='tipo_contrato', max_length=50, null=True)),
                ('salario_base_q', models.DecimalField(db_column='salario_base_q', decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_contratacion', models.DateField(db_column='fecha_contratacion')),
                ('fecha_baja', models.DateField(blank=True, db_column='fecha_baja', null=True)),
                ('usuario_id', models.IntegerField(blank=True, db_column='usuario_id', null=True)),
                ('activo', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'ordering': ['codigo_empleado'],
                'indexes': [models.Index(fields=['codigo_empleado'], name='idx_empleados_codigo'), models.Index(fields=['dpi'], name='idx_empleados_dpi'), models.Index(fields=['nombres', 'apellidos'], name='idx_empleados_nombre'), models.Index(fields=['puesto'], name='idx_empleados_puesto'), models.Index(fields=['activo'], name='idx_empleados_activo')],
            },
        ),
    ]
